version: "3.8"
services:
  backend:
    build:
      dockerfile: Dockerfile.backend
      args:
        APP_SECRET: "secret"
    ports:
      - "8080:8080"
    environment:
     - MONGODB_URL=mongodb://db:27017/ts-chat-app'

  frontend:
    build:
      dockerfile: Dockerfile.frontend
      args:
        APP_CHATAPP_API: http://localhost:8080
    ports:
      - "3000:3000"
      
  db:
    image: mongo:6.0.2
    ports:
      - "27017:27017"
    container_name: db
    volumes:
      - /data/db
      