FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./frontend/package*.json ./frontend/
# COPY ./shared/package*json ./

RUN npm ci -w frontend

COPY ./frontend/ ./frontend/
# COPY ./shared/ ./shared/

ARG APP_CHATAPP_API
ENV REACT_APP_CHATAPP_API=${APP_CHATAPP_API}

RUN npm run build -w frontend

EXPOSE 3000

CMD [ "npx", "serve", "-s", "frontend/build"]