FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./backend/package*.json ./backend/

RUN npm ci -w backend

COPY ./backend/ ./backend/

ARG APP_SECRET
ENV SESSION_SECRET=${APP_SECRET}

RUN npm run build -w backend

EXPOSE 8080

CMD [ "node", "backend/dist/src/app.js"]