FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./backend/package*.json ./backend/
# COPY ./shared/package*json ./

RUN npm ci -w backend

COPY ./backend/ ./backend/
# COPY ./shared/ ./shared/

RUN npm run build -w backend

EXPOSE 8080

CMD [ "node", "backend/dist/src/app.js"]